name: Website Checker

on:
  push:
    branches:
      - main  
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check-website:
    runs-on: ubuntu-latest

    env:
      NPS_URL_PROD: ${{ secrets.NPS_URL_PROD }}  # Use the secret here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

      env:
        PYTHONPATH: ${{ github.workspace }}/checker

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest and capture results
      run: pytest -n auto --junitxml=results.xml

    - name: Parse and send test results to Telegram
      id: parse_and_send  # Add an ID to the step
      run: |
        python parse/parse_results.py  # Run your Python script to parse results
        cat parse/test_results.txt     # Print the parsed results
        echo "::set-output name=results::$(cat test_results.txt)"  # Set an output for the step
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Send Telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          GitHub Actions: Website checker completed.
          Test Results:
          ${{ steps.parse_and_send.outputs.results }}  # Use the output from the previous step
