name: Website Checker

on:
  push:
    branches:
      - main  
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Python Path
      run: echo "::add-path::${{ github.workspace }}/checker"

    - name: Run tests with pytest
      run: pytest -n auto --github-report

    # - name: Send Telegram message
    #   uses: appleboy/telegram-action@0.1.2
    #   with:
    #     to: ${{ secrets.TELEGRAM_CHAT_ID }}
    #     token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    #     message: |
    #       GitHub Actions: Website checker completed.
