name: Website Checker

on:
  push:
    branches:
      - main  
#  schedule:
#    - cron: '*/30 * * * *'

jobs:
  check-website:
    runs-on: ubuntu-latest

    env:
      NPS_URL_PROD: ${{ secrets.NPS_URL_PROD }}
      NPG_URL_PROD: ${{ secrets.NPG_URL_PROD}}
      NPG_URL_STAGE: ${{ secrets.NPG_URL_STAGE}}
      NPG_ADMIN_EMAIL: ${{ secrets.NPG_ADMIN_EMAIL}}
      NPG_ADMIN_PASS: ${{ secrets.NPG_ADMIN_PASS}}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

      env:
        PYTHONPATH: ${{ github.workspace }}/checker

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest and capture results
      run: pytest -rA | tee test_results.txt

    - name: Send to Telegram
      run: python3 telegram_sending.py


